import 'package:path/path.dart' as p;
import 'package:tools/tools.dart';

Future<void> generateFeatureDocumentation() async {
  printSection('📚 Automated Feature Documentation');

  final activePath = getActiveProjectPath();
  final featuresDir = Directory(p.join(activePath, 'lib', 'features'));

  if (!featuresDir.existsSync()) {
    printError('lib/features directory not found.');
    return;
  }

  final features = featuresDir.listSync().whereType<Directory>();
  if (features.isEmpty) {
    printWarning('No features found to document.');
    return;
  }

  await loadingSpinner(
    'Analyzing and documenting features in $activePath',
    () async {
      for (final featureDir in features) {
        final featureName = p.basename(featureDir.path);
        if (featureName.startsWith('z_')) continue;

        final buffer = StringBuffer();
        buffer.writeln('# 📦 Feature: ${featureName.toUpperCase()}');
        buffer.writeln('\nGenerated by Tronixbyte Elite CLI\n');

        // 1. Analyze UseCases
        final useCasesDir = Directory(
          p.join(featureDir.path, 'domain', 'usecases'),
        );
        if (useCasesDir.existsSync()) {
          buffer.writeln('## ⚙️ Business Logic (UseCases)');
          final files = useCasesDir.listSync().whereType<File>().where(
            (f) =>
                f.path.endsWith('.dart') &&
                !p.basename(f.path).startsWith('z_'),
          );
          for (final file in files) {
            final name = p.basenameWithoutExtension(file.path);
            buffer.writeln('- **$name**: Core business logic implementation.');
          }
          buffer.writeln('');
        }

        // 2. Analyze Models & Entities
        final entitiesDir = Directory(
          p.join(featureDir.path, 'domain', 'entities'),
        );
        if (entitiesDir.existsSync()) {
          buffer.writeln('## 📄 Data Structures');
          final files = entitiesDir.listSync().whereType<File>().where(
            (f) =>
                f.path.endsWith('.dart') &&
                !p.basename(f.path).startsWith('z_'),
          );
          for (final file in files) {
            final name = p.basenameWithoutExtension(file.path);
            buffer.writeln('- **$name**: Domain entity representation.');
          }
          buffer.writeln('');
        }

        // 3. Analyze UI
        final screensDir = Directory(
          p.join(featureDir.path, 'presentation', 'screens'),
        );
        if (screensDir.existsSync()) {
          buffer.writeln('## 📱 Presentation Layer');
          final files = screensDir.listSync().whereType<File>().where(
            (f) =>
                f.path.endsWith('.dart') &&
                !p.basename(f.path).startsWith('z_'),
          );
          for (final file in files) {
            final name = p.basenameWithoutExtension(file.path);
            buffer.writeln('- **$name**: Main user interface screen.');
          }
          buffer.writeln('');
        }

        buffer.writeln('---');
        buffer.writeln(
          '*This feature follows strict Clean Architecture standards.*',
        );

        final readmeFile = File(p.join(featureDir.path, 'README.md'));
        readmeFile.writeAsStringSync(buffer.toString());
      }
    },
  );

  printSuccess('Feature-level documentation generated for all modules.');
  ask('Press Enter to return');
}
