import 'package:path/path.dart' as p;
import 'package:tools/tools.dart';

Future<void> manageDependencies() async {
  while (true) {
    final options = [
      'Add Dependency',
      'Remove Dependency',
      'Upgrade All Dependencies (Major Versions)',
      'Find Unused Dependencies (Cleanup)',
      'Sync global.dart with pubspec.yaml',
      'Check for Outdated Packages',
      'Dependency Security Guard (CVE Scan)',
      'OWASP Dependency Audit (OSV.dev)',
    ];

    final choice = selectOption(
      'Tronixbyte Dependency Manager',
      options,
      showBack: true,
    );

    switch (choice) {
      case '1':
        await _addDependency();
        break;
      case '2':
        await _removeDependency();
        break;
      case '3':
        await _upgradeDependencies();
        break;
      case '4':
        await findUnusedDependencies();
        break;
      case '5':
        await syncGlobalExports();
        break;
      case '6':
        // runCommand uses getActiveProjectPath() internally
        await runCommand('flutter', ['pub', 'outdated']);
        break;
      case '7':
        await runDependencySecurityScan();
        break;
      case '8':
        await runOwaspDependencyAudit();
        break;
      case 'back':
        return;
      case null:
        break;
      default:
        printError('Invalid option.');
    }
  }
}

Future<void> _addDependency() async {
  final name = ask('Enter package name to ADD');
  if (name == null || name.isEmpty) return;

  final isDev =
      (ask('Is this a dev_dependency? (y/n)') ?? 'n').toLowerCase() == 'y';

  await runCommand('flutter', [
    'pub',
    'add',
    if (isDev) '--dev',
    name,
  ], loadingMessage: 'Adding $name');

  if (!isDev) {
    await syncGlobalExports();
  }
}

Future<void> _removeDependency() async {
  final name = ask('Enter package name to REMOVE');
  if (name == null || name.isEmpty) return;

  await runCommand('flutter', [
    'pub',
    'remove',
    name,
  ], loadingMessage: 'Removing $name');
  await syncGlobalExports();
}

Future<void> _upgradeDependencies() async {
  await runCommand('flutter', [
    'pub',
    'upgrade',
    '--major-versions',
  ], loadingMessage: 'Upgrading all dependencies');
  await syncGlobalExports();
  printSuccess('Upgrade complete and global.dart synchronized.');
}

Future<void> syncGlobalExports() async {
  final activePath = getActiveProjectPath();
  final pubspec = File(p.join(activePath, 'pubspec.yaml'));

  if (!pubspec.existsSync()) {
    printError('pubspec.yaml not found at ${pubspec.path}.');
    return;
  }

  await loadingSpinner(
    'Syncing lib/src/global.dart with pubspec.yaml in $activePath',
    () async {
      final content = pubspec.readAsStringSync();
      final lines = content.split(RegExp(r'\r?\n'));
      bool inDeps = false;
      final List<String> packageNames = [];

      for (var line in lines) {
        final trimmedLine = line.trim();

        if (trimmedLine == 'dependencies:') {
          inDeps = true;
          continue;
        }

        if (inDeps) {
          if (line.isNotEmpty &&
              !line.startsWith(' ') &&
              !line.startsWith('#')) {
            inDeps = false;
            continue;
          }

          if (line.startsWith('  ') && !line.startsWith('   ')) {
            final trimmed = line.trim();
            if (trimmed.isEmpty || trimmed.startsWith('#')) continue;

            final parts = trimmed.split(':');
            final name = parts.first.trim();

            if (name.isNotEmpty &&
                name != 'flutter' &&
                name != 'sdk' &&
                !name.startsWith('flutter_test')) {
              packageNames.add(name);
            }
          }
        }
      }

      final buffer = StringBuffer();
      buffer.writeln('// Generated by Tronixbyte CLI - Global Exports');
      buffer.writeln(
        "// This file contains exports of all project dependencies.\n",
      );

      final uniqueDeps = packageNames.toSet().toList()..sort();

      for (var pkg in uniqueDeps) {
        buffer.writeln("export 'package:$pkg/$pkg.dart';");
      }

      final globalFile = File(p.join(activePath, 'lib', 'src', 'global.dart'));
      if (!globalFile.parent.existsSync()) {
        globalFile.parent.createSync(recursive: true);
      }
      globalFile.writeAsStringSync(buffer.toString(), mode: FileMode.write);
    },
  );

  printSuccess('lib/src/global.dart updated successfully in active project.');
}
