import 'package:path/path.dart' as p;
import 'package:tools/tools.dart';

Future<void> generateFeaturesOverview() async {
  printSection('Features Overview Generator');

  final featuresDir = Directory('lib/features');
  if (!featuresDir.existsSync()) {
    printError('lib/features directory not found.');
    return;
  }

  await loadingSpinner('Generating FEATURES.md', () async {
    final buffer = StringBuffer();
    buffer.writeln('# 🧩 Project Features Overview');
    buffer.writeln(
      '\nThis file is automatically generated. It tracks the implementation status of all modules.\n',
    );
    buffer.writeln(
      '| Feature | Domain | Data | Presentation | Tests | Status |',
    );
    buffer.writeln('| :--- | :---: | :---: | :---: | :---: | :--- |');

    final features = featuresDir
        .listSync()
        .whereType<Directory>()
        .where((d) => !p.basename(d.path).startsWith('z_'))
        .toList();

    for (final feature in features) {
      final name = p.basename(feature.path);
      final hasDomain = Directory(p.join(feature.path, 'domain')).existsSync();
      final hasData = Directory(p.join(feature.path, 'data')).existsSync();
      final hasPresentation = Directory(
        p.join(feature.path, 'presentation'),
      ).existsSync();

      final testDir = Directory(p.join('test', 'features', name));
      final hasTests =
          testDir.existsSync() &&
          testDir
              .listSync(recursive: true)
              .any((e) => e.path.endsWith('_test.dart'));

      final layersCount = [
        hasDomain,
        hasData,
        hasPresentation,
      ].where((e) => e).length;

      String status = '🏗️ In Progress';
      if (layersCount == 3 && hasTests) {
        status = '✅ Complete';
      } else if (layersCount == 3) {
        status = '🧪 Missing Tests';
      } else if (layersCount == 0) {
        status = '📁 Empty Shell';
      }

      buffer.writeln(
        '| ${name[0].toUpperCase()}${name.substring(1)} '
        '| ${hasDomain ? '✅' : '❌'} '
        '| ${hasData ? '✅' : '❌'} '
        '| ${hasPresentation ? '✅' : '❌'} '
        '| ${hasTests ? '✅' : '❌'} '
        '| $status |',
      );
    }

    File('FEATURES.md').writeAsStringSync(buffer.toString());
  });

  printSuccess('FEATURES.md generated successfully at the project root.');
}
