import 'package:path/path.dart' as p;
import 'package:tools/tools.dart';

Future<void> runProductionAudit() async {
  printSection('Production Readiness Auditor');

  final activePath = getActiveProjectPath();
  int issues = 0;
  int checks = 0;
  List<String> details = [];
  final List<Map<String, dynamic>> autoFixes = [];

  void report(
    String name,
    bool success,
    String message, {
    List<String>? items,
    Future<void> Function()? fix,
  }) {
    checks++;
    if (success) {
      printSuccess('$name: Pass');
    } else {
      printError('$name: FAIL - $message');
      issues++;
      if (items != null && items.isNotEmpty) {
        details.add('\n      $name Issues:');
        details.addAll(items.map((e) => '      - $e'));
      }
      if (fix != null) {
        autoFixes.add({'name': name, 'fix': fix});
      }
    }
  }

  // 1. Min SDK Check
  final gradleFile = File(p.join(activePath, 'android/app/build.gradle'));
  if (gradleFile.existsSync()) {
    final content = gradleFile.readAsStringSync();
    final minSdkMatch = RegExp(r'minSdkVersion\s+(\d+)').firstMatch(content);
    if (minSdkMatch != null) {
      final val = int.parse(minSdkMatch.group(1)!);
      report(
        'Min SDK Version',
        val >= 21,
        'Version $val found. 21+ is recommended.',
        fix: () async {
          final newContent = content.replaceFirst(
            minSdkMatch.group(0)!,
            'minSdkVersion 21',
          );
          gradleFile.writeAsStringSync(newContent);
        },
      );
    }
  }

  // 2. Obfuscation Check
  final proguard = File(p.join(activePath, 'android/app/proguard-rules.pro'));
  report(
    'Android Obfuscation',
    proguard.existsSync(),
    'proguard-rules.pro missing.',
    fix: () async {
      if (!proguard.existsSync()) {
        if (!proguard.parent.existsSync()) {
          proguard.parent.createSync(recursive: true);
        }
        proguard.writeAsStringSync(
          '# Proguard rules generated by Tronixbyte CLI\n-keep class **.ExternalModel { *; }\n',
        );
      }
    },
  );

  // 3. Icon Completeness
  final icons = Directory(p.join(activePath, 'assets/images'));
  final hasIcons =
      icons.existsSync() &&
      icons.listSync().any(
        (e) => e.path.contains('logo') || e.path.contains('icon'),
      );
  report('App Icons', hasIcons, 'No icon-like files found in assets/images.');

  // 4. Environment Check
  final prodEnv = File(p.join(activePath, '.env.prod'));
  final devEnv = File(p.join(activePath, '.env.dev'));
  if (prodEnv.existsSync() && devEnv.existsSync()) {
    final prodContent = prodEnv.readAsStringSync();
    final devContent = devEnv.readAsStringSync();
    report(
      'Environment Sync',
      prodContent != devContent,
      '.env.prod is identical to .env.dev. Check your secrets!',
    );
  } else {
    report('Prod Environment', prodEnv.existsSync(), '.env.prod is missing.');
  }

  // 5. No print() or debugPrint() calls
  final libDir = Directory(p.join(activePath, 'lib'));
  List<String> printCalls = [];
  if (libDir.existsSync()) {
    final files = libDir
        .listSync(recursive: true)
        .whereType<File>()
        .where((f) => f.path.endsWith('.dart'));
    for (final file in files) {
      final content = file.readAsStringSync();
      if (content.contains('print(') || content.contains('debugPrint(')) {
        printCalls.add(p.relative(file.path, from: activePath));
      }
    }
  }
  report(
    'No print/debugPrint calls',
    printCalls.isEmpty,
    'Found ${printCalls.length} print/debugPrint calls.',
    items: printCalls,
  );

  // 6. Hardcoded URL Detection
  List<String> hardcodedUrls = [];
  final urlPattern = RegExp(r"https?://[^\s'\\]+");
  if (libDir.existsSync()) {
    final files = libDir
        .listSync(recursive: true)
        .whereType<File>()
        .where((f) => f.path.endsWith('.dart'));
    for (final file in files) {
      final content = file.readAsStringSync();
      if (urlPattern.hasMatch(content)) {
        hardcodedUrls.add(p.relative(file.path, from: activePath));
      }
    }
  }
  report(
    'Hardcoded URLs',
    hardcodedUrls.isEmpty,
    'Found ${hardcodedUrls.length} hardcoded URLs.',
    items: hardcodedUrls,
  );

  // 7. Linter Presence Check
  final pubspecFile = File(p.join(activePath, 'pubspec.yaml'));
  bool hasLints = false;
  if (pubspecFile.existsSync()) {
    final content = pubspecFile.readAsStringSync();
    hasLints = content.contains('flutter_lints:');
  }
  report(
    'Linter Presence',
    hasLints,
    'flutter_lints missing in pubspec.yaml.',
    fix: () async {
      await runCommand('flutter', ['pub', 'add', 'dev:flutter_lints']);
    },
  );

  if (details.isNotEmpty) {
    print('\n$yellow${bold}AUDIT DETAILS for $activePath:$reset');
    details.forEach(print);
  }

  print('\n$blue$bold${'=' * 60}$reset');
  print(
    '🏁 Audit complete: $checks checks, ${checks - issues} passed, $issues failed.',
  );

  if (issues == 0) {
    printSuccess('STATUS: Your project is READY FOR PRODUCTION!');
  } else {
    printWarning('STATUS: Please address the issues above before releasing.');

    if (autoFixes.isNotEmpty) {
      print('\n$cyan$bold🛠️  SELF-HEALING AVAILABLE:$reset');
      for (final af in autoFixes) {
        print('   - ${af['name']}');
      }
      final fixAll =
          (ask(
                    'Would you like to attempt auto-fixing these ${autoFixes.length} issues? (y/n)',
                    defaultValue: 'n',
                  ) ??
                  'n')
              .toLowerCase() ==
          'y';

      if (fixAll) {
        await loadingSpinner('Healing production configuration', () async {
          for (final af in autoFixes) {
            final Future<void> Function() fixFn = af['fix'];
            await fixFn();
          }
        });
        printSuccess(
          'Self-healing complete. Please re-run the audit to verify.',
        );
      }
    }
  }
}
