import 'package:path/path.dart' as p;
import 'package:tools/tools.dart';

Future<void> generateAssetConstants() async {
  printSection('Asset Constants Generator');

  final activePath = getActiveProjectPath();
  final assetsDir = Directory(p.join(activePath, 'assets'));

  if (!assetsDir.existsSync()) {
    printError('assets/ directory not found at ${assetsDir.path}.');
    return;
  }

  await loadingSpinner(
    'Scanning and generating asset constants in $activePath',
    () async {
      final buffer = StringBuffer();
      buffer.writeln('// Generated by Tronixbyte CLI - DO NOT MODIFY BY HAND');
      buffer.writeln('class AppAssets {');

      final entities = assetsDir.listSync(recursive: true);
      entities.sort((a, b) => a.path.compareTo(b.path));

      for (final entity in entities) {
        if (entity is File) {
          final relativePath = p
              .relative(entity.path, from: activePath)
              .replaceAll('\\', '/');
          final fileName = p.basenameWithoutExtension(entity.path);
          final extension = p.extension(entity.path).toLowerCase();

          // Skip system files and specific asset types like translations
          if (fileName.startsWith('.') ||
              extension == '.db' ||
              (extension == '.json' && relativePath.contains('translations'))) {
            continue;
          }

          final variableName = _toCamelCase(fileName);
          buffer.writeln(
            '  static const String $variableName = \'$relativePath\';',
          );
        }
      }

      buffer.writeln('}');

      final outFile = File(
        p.join(activePath, 'lib/core/constants/app_assets.dart'),
      );
      if (!outFile.parent.existsSync()) {
        outFile.parent.createSync(recursive: true);
      }
      outFile.writeAsStringSync(buffer.toString());

      // Update Core Barrel
      _updateCoreConstantsBarrel(activePath);
    },
  );

  printSuccess('Generated: lib/core/constants/app_assets.dart');
}

void _updateCoreConstantsBarrel(String activePath) {
  final barrelFile = File(
    p.join(activePath, 'lib/core/constants/z_constants.dart'),
  );
  const exportLine = "export 'app_assets.dart';";

  if (!barrelFile.existsSync()) {
    barrelFile.writeAsStringSync('$exportLine\n');
  } else {
    final content = barrelFile.readAsStringSync();
    if (!content.contains('app_assets.dart')) {
      barrelFile.writeAsStringSync('$content$exportLine\n');
    }
  }
}

String _toCamelCase(String text) {
  final words = text.split(RegExp(r'[^a-zA-Z0-9]'));
  if (words.isEmpty) return text;

  final result = StringBuffer(words[0].toLowerCase());
  for (int i = 1; i < words.length; i++) {
    if (words[i].isEmpty) continue;
    result.write(
      words[i][0].toUpperCase() + words[i].substring(1).toLowerCase(),
    );
  }
  return result.toString();
}
